#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : keepalived
Version  : 2.0.20
Release  : 14
URL      : http://www.keepalived.org/software/keepalived-2.0.20.tar.gz
Source0  : http://www.keepalived.org/software/keepalived-2.0.20.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: keepalived-bin = %{version}-%{release}
Requires: keepalived-license = %{version}-%{release}
Requires: keepalived-man = %{version}-%{release}
Requires: keepalived-services = %{version}-%{release}
BuildRequires : dbus-dev
BuildRequires : file-dev
BuildRequires : glibc-bin
BuildRequires : grep
BuildRequires : ipset-dev
BuildRequires : libnl-dev
BuildRequires : nftables-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(libnfnetlink)
BuildRequires : sed

%description
The main goal of the keepalived project is to add a strong & robust
keepalive facility to the Linux Virtual Server project.
It implements a multilayer TCP/IP stack checks. Keepalived implements
a framework based on three family checks : Layer3, Layer4 & Layer5.
This framework gives the daemon the ability of checking a LVS server
pool states. Keepalived can be sumarize as a LVS driving daemon.

%package bin
Summary: bin components for the keepalived package.
Group: Binaries
Requires: keepalived-license = %{version}-%{release}
Requires: keepalived-services = %{version}-%{release}

%description bin
bin components for the keepalived package.


%package doc
Summary: doc components for the keepalived package.
Group: Documentation
Requires: keepalived-man = %{version}-%{release}

%description doc
doc components for the keepalived package.


%package license
Summary: license components for the keepalived package.
Group: Default

%description license
license components for the keepalived package.


%package man
Summary: man components for the keepalived package.
Group: Default

%description man
man components for the keepalived package.


%package services
Summary: services components for the keepalived package.
Group: Systemd services

%description services
services components for the keepalived package.


%prep
%setup -q -n keepalived-2.0.20
cd %{_builddir}/keepalived-2.0.20

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644104196
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static --with-init=systemd \
--with-systemdsystemunitdir=/usr/lib/systemd/system
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1644104196
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/keepalived
cp %{_builddir}/keepalived-2.0.20/COPYING %{buildroot}/usr/share/package-licenses/keepalived/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/keepalived-2.0.20/doc/source/license.rst %{buildroot}/usr/share/package-licenses/keepalived/d73d4816cf634ff133308566be305c1d092cd941
cp %{_builddir}/keepalived-2.0.20/genhash/COPYING %{buildroot}/usr/share/package-licenses/keepalived/075d599585584bb0e4b526f5c40cb6b17e0da35a
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/genhash
/usr/bin/keepalived

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/keepalived/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/keepalived/075d599585584bb0e4b526f5c40cb6b17e0da35a
/usr/share/package-licenses/keepalived/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/keepalived/d73d4816cf634ff133308566be305c1d092cd941

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/genhash.1
/usr/share/man/man5/keepalived.conf.5
/usr/share/man/man8/keepalived.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/keepalived.service
