#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : keepalived
Version  : 2.0.7
Release  : 1
URL      : http://www.keepalived.org/software/keepalived-2.0.7.tar.gz
Source0  : http://www.keepalived.org/software/keepalived-2.0.7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: keepalived-bin
Requires: keepalived-license
Requires: keepalived-man
BuildRequires : glibc-bin
BuildRequires : grep
BuildRequires : openssl-dev
BuildRequires : pkgconfig(systemd)
BuildRequires : sed
BuildRequires : systemd-dev

%description
The main goal of the keepalived project is to add a strong & robust
keepalive facility to the Linux Virtual Server project.
It implements a multilayer TCP/IP stack checks. Keepalived implements
a framework based on three family checks : Layer3, Layer4 & Layer5.
This framework gives the daemon the ability of checking a LVS server
pool states. Keepalived can be sumarize as a LVS driving daemon.

%package bin
Summary: bin components for the keepalived package.
Group: Binaries
Requires: keepalived-license
Requires: keepalived-man

%description bin
bin components for the keepalived package.


%package doc
Summary: doc components for the keepalived package.
Group: Documentation
Requires: keepalived-man

%description doc
doc components for the keepalived package.


%package license
Summary: license components for the keepalived package.
Group: Default

%description license
license components for the keepalived package.


%package man
Summary: man components for the keepalived package.
Group: Default

%description man
man components for the keepalived package.


%prep
%setup -q -n keepalived-2.0.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535077159
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1535077159
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/keepalived
cp COPYING %{buildroot}/usr/share/doc/keepalived/COPYING
cp genhash/COPYING %{buildroot}/usr/share/doc/keepalived/genhash_COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/genhash
/usr/bin/keepalived

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/keepalived/*

%files license
%defattr(-,root,root,-)
/usr/share/doc/keepalived/COPYING
/usr/share/doc/keepalived/genhash_COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/genhash.1
/usr/share/man/man5/keepalived.conf.5
/usr/share/man/man8/keepalived.8
